# Generated by Django 4.1.1 on 2022-12-14 20:08

import client.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(help_text='الرقم القومى مكون من 14 رقم ', max_length=14, unique=True, validators=[client.models.national_id])),
                ('type', models.CharField(choices=[('trade', 'Trade'), ('customer', 'Customer')], default='customer', help_text='نوع العميل ', max_length=20)),
                ('name', models.CharField(help_text='الاسم  يجب ان  يكون رسمى يدون تكرار', max_length=50, unique=True, validators=[client.models.validation_name])),
                ('phone1', models.CharField(help_text='رقم الموبايل', max_length=11, unique=True, validators=[client.models.validation_phone])),
                ('phone2', models.CharField(blank=True, help_text='رقم الموبايل', max_length=11, null=True, unique=True, validators=[client.models.validation_phone])),
                ('place', models.CharField(blank=True, help_text='العنوان', max_length=50, null=True)),
                ('img', models.ImageField(default='F:/AppDjango/Katkout/media/client/image/Hamdy.JPG', help_text='الصورة ', upload_to='client/image')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
