# Generated by Django 4.1.1 on 2022-12-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment', models.CharField(help_text='المدفوع من الفاتورة ', max_length=4)),
                ('remaining_amount', models.CharField(help_text='الباقى من الفاتورة ', max_length=4)),
                ('data_payment', models.DateTimeField(auto_now_add=True)),
                ('data_remaining_amount', models.DateField(help_text='تاريخ تسديد باقى الفاتورة')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('client', models.ForeignKey(help_text='صاحب الفاتورة', on_delete=django.db.models.deletion.CASCADE, related_name='client_bill', to='client.client')),
                ('user', models.ForeignKey(help_text='مسجل الفاتورة', on_delete=django.db.models.deletion.PROTECT, related_name='user_bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOfGoods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='اسم البطاعة', max_length=20)),
                ('number', models.CharField(help_text='عدد  البطاعة التى تم شراؤها', max_length=20)),
                ('price', models.CharField(help_text=' سعر وحده من البضاعة التى تم شراؤها ', max_length=20)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('bill', models.ForeignKey(help_text='  رقم الفاتورة', on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='bill.bill')),
                ('client', models.ForeignKey(help_text='صاحب شراء البضاعة', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
                ('user', models.ForeignKey(help_text='مسجل بيع البضاعة', on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
