# Generated by Django 4.1.1 on 2022-12-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='purchaseofgoods',
            name='slug',
        ),
    ]
